#!/command/with-contenv bash

s6-echo "Starting unbound"

NAME="unbound"
DESC="DNS server"
DAEMON="/usr/sbin/unbound"
PIDFILE="/run/unbound.pid"

HELPER="/usr/lib/unbound/package-helper"

test -x  || exit 0

# Override this variable by editing or creating /etc/default/unbound.
DAEMON_OPTS=""

if [ -f /etc/default/unbound ]; then
    . /etc/default/unbound
fi

 chroot_setup
 root_trust_anchor_update 2>&1 | logger -p daemon.info -t unbound-anchor

 -d 

