name: Nightly

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: git.fave.lu
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}      
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags:  git.fave.lu/fave/pihole-unbound:latest
          push: false
